name: Build Docker

on:
  pull_request:
    paths:
      - "Dockerfile"
      - "docker-compose.yml"

jobs:
  build:
    name: Build Docker
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build HORNET Docker image
        run: docker build . --file Dockerfile --tag hornet:latest

      - name: Test HORNET Docker image
        run: docker run --rm --name hornet hornet:latest --version 2>/dev/null | grep -q "HORNET"
