name: Build HORNET

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - 'nfpm/**'
      - 'private_tangle/**'
      - 'scripts/**'
      - 'tools/**'

jobs:
  build:
    name: Build HORNET
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Print Go version
        run: go version

      - name: Build HORNET
        run: go build -v .
