name: Test HORNET

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - 'nfpm/**'
      - 'private_tangle/**'
      - 'scripts/**'
      - 'tools/**'

jobs:
  test:
    name: Test HORNET
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Print Go version
        run: go version

      - name: Install Build Essential
        run: sudo apt update && sudo apt install build-essential -y

      - name: Test HORNET
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: go test `go list ./... | grep -v -e integration-tests`
